spring:
  application:
    name:Event
  datasource:
    url: jdbc:mariadb://localhost:3306/event
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
server:
  port: 9999
